# Deye SG04LP3 - Three Phase Low Voltage Hybrid Inverter
# Models: SUN-8K/10K/12K-SG04LP3-EU

metadata:
  manufacturer: "Deye"
  model: "SG04LP3"
  description: "Three Phase Low Voltage Hybrid Inverter (8-12kW)"
  voltage: "LV"
  supported_models:
    - "SUN-8K-SG04LP3-EU"
    - "SUN-10K-SG04LP3-EU"
    - "SUN-12K-SG04LP3-EU"

connection:
  timeout: 10
  batch_size: 10

# Include common sensor packages
includes:
  - deye/common/inverter.yaml
  - deye/common/battery.yaml
  - deye/common/grid_3p.yaml
  - deye/common/load_3p.yaml
  - deye/common/pv1.yaml
  - deye/common/pv2.yaml
  - deye/common/pv.yaml

# Add new sensors or override common sensors
sensors:
  
