# JK BMS Complete Template
# Based on reference documentation from .referenceCode3
# Trame 3 - Live Data (Register 5664/0x1620)

metadata:
  manufacturer: "JKong"
  model: "JK-BMS"
  description: "JK Battery Management System (Complete Template)"
  voltage: "LV"
  supported_models:
    - "JK-B2A24S"
    - "JK-B1A24S"
    - "JK-B2A20S"

connection:
  timeout: 5
  batch_size: 150

sensors:
  # ===== Cell Voltages (Offset 6-36, uint16le) =====
  cell_1_voltage:
    name: "Cell 1 Voltage"
    address: 5667  # Base 5664 + offset 3 (6/2)
    data_type: uint16
    factor: 0.001
    unit: "V"
    device_class: "voltage"
  
  cell_2_voltage:
    name: "Cell 2 Voltage"
    address: 5668
    data_type: uint16
    factor: 0.001
    unit: "V"
    device_class: "voltage"
  
  cell_3_voltage:
    name: "Cell 3 Voltage"
    address: 5669
    data_type: uint16
    factor: 0.001
    unit: "V"
    device_class: "voltage"
  
  cell_4_voltage:
    name: "Cell 4 Voltage"
    address: 5670
    data_type: uint16
    factor: 0.001
    unit: "V"
    device_class: "voltage"
  
  cell_5_voltage:
    name: "Cell 5 Voltage"
    address: 5671
    data_type: uint16
    factor: 0.001
    unit: "V"
    device_class: "voltage"
  
  cell_6_voltage:
    name: "Cell 6 Voltage"
    address: 5672
    data_type: uint16
    factor: 0.001
    unit: "V"
    device_class: "voltage"
  
  cell_7_voltage:
    name: "Cell 7 Voltage"
    address: 5673
    data_type: uint16
    factor: 0.001
    unit: "V"
    device_class: "voltage"
  
  cell_8_voltage:
    name: "Cell 8 Voltage"
    address: 5674
    data_type: uint16
    factor: 0.001
    unit: "V"
    device_class: "voltage"
  
  cell_9_voltage:
    name: "Cell 9 Voltage"
    address: 5675
    data_type: uint16
    factor: 0.001
    unit: "V"
    device_class: "voltage"
  
  cell_10_voltage:
    name: "Cell 10 Voltage"
    address: 5676
    data_type: uint16
    factor: 0.001
    unit: "V"
    device_class: "voltage"
  
  cell_11_voltage:
    name: "Cell 11 Voltage"
    address: 5677
    data_type: uint16
    factor: 0.001
    unit: "V"
    device_class: "voltage"
  
  cell_12_voltage:
    name: "Cell 12 Voltage"
    address: 5678
    data_type: uint16
    factor: 0.001
    unit: "V"
    device_class: "voltage"
  
  cell_13_voltage:
    name: "Cell 13 Voltage"
    address: 5679
    data_type: uint16
    factor: 0.001
    unit: "V"
    device_class: "voltage"
  
  cell_14_voltage:
    name: "Cell 14 Voltage"
    address: 5680
    data_type: uint16
    factor: 0.001
    unit: "V"
    device_class: "voltage"
  
  cell_15_voltage:
    name: "Cell 15 Voltage"
    address: 5681
    data_type: uint16
    factor: 0.001
    unit: "V"
    device_class: "voltage"
  
  cell_16_voltage:
    name: "Cell 16 Voltage"
    address: 5682
    data_type: uint16
    factor: 0.001
    unit: "V"
    device_class: "voltage"

  # ===== Cell Resistances (Offset 80-110, int16le) =====
  cell_1_resistance:
    name: "Cell 1 Resistance"
    address: 5704  # Base 5664 + offset 40 (80/2)
    data_type: int16
    factor: 0.001
    unit: "Ω"
  
  cell_2_resistance:
    name: "Cell 2 Resistance"
    address: 5705
    data_type: int16
    factor: 0.001
    unit: "Ω"
  
  cell_3_resistance:
    name: "Cell 3 Resistance"
    address: 5706
    data_type: int16
    factor: 0.001
    unit: "Ω"
  
  cell_4_resistance:
    name: "Cell 4 Resistance"
    address: 5707
    data_type: int16
    factor: 0.001
    unit: "Ω"
  
  cell_5_resistance:
    name: "Cell 5 Resistance"
    address: 5708
    data_type: int16
    factor: 0.001
    unit: "Ω"
  
  cell_6_resistance:
    name: "Cell 6 Resistance"
    address: 5709
    data_type: int16
    factor: 0.001
    unit: "Ω"
  
  cell_7_resistance:
    name: "Cell 7 Resistance"
    address: 5710
    data_type: int16
    factor: 0.001
    unit: "Ω"
  
  cell_8_resistance:
    name: "Cell 8 Resistance"
    address: 5711
    data_type: int16
    factor: 0.001
    unit: "Ω"
  
  cell_9_resistance:
    name: "Cell 9 Resistance"
    address: 5712
    data_type: int16
    factor: 0.001
    unit: "Ω"
  
  cell_10_resistance:
    name: "Cell 10 Resistance"
    address: 5713
    data_type: int16
    factor: 0.001
    unit: "Ω"
  
  cell_11_resistance:
    name: "Cell 11 Resistance"
    address: 5714
    data_type: int16
    factor: 0.001
    unit: "Ω"
  
  cell_12_resistance:
    name: "Cell 12 Resistance"
    address: 5715
    data_type: int16
    factor: 0.001
    unit: "Ω"
  
  cell_13_resistance:
    name: "Cell 13 Resistance"
    address: 5716
    data_type: int16
    factor: 0.001
    unit: "Ω"
  
  cell_14_resistance:
    name: "Cell 14 Resistance"
    address: 5717
    data_type: int16
    factor: 0.001
    unit: "Ω"
  
  cell_15_resistance:
    name: "Cell 15 Resistance"
    address: 5718
    data_type: int16
    factor: 0.001
    unit: "Ω"
  
  cell_16_resistance:
    name: "Cell 16 Resistance"
    address: 5719
    data_type: int16
    factor: 0.001
    unit: "Ω"

  # ===== Temperatures =====
  mosfet_temperature:
    name: "MOSFET Temperature"
    address: 5736  # Offset 144 (base 5664 + 72 regs = 5736)
    data_type: int16
    factor: 0.1
    unit: "°C"
    device_class: "temperature"
  
  temperature_sensor_1:
    name: "Temperature Sensor 1"
    address: 5745  # Offset 162 (base 5664 + 81 regs = 5745)
    data_type: int16
    factor: 0.1
    unit: "°C"
    device_class: "temperature"
  
  temperature_sensor_2:
    name: "Temperature Sensor 2"
    address: 5746  # Offset 164 (base 5664 + 82 regs = 5746)
    data_type: int16
    factor: 0.1
    unit: "°C"
    device_class: "temperature"
  
  temperature_sensor_3:
    name: "Temperature Sensor 3"
    address: 5791  # Offset 254 (base 5664 + 127 regs = 5791)
    data_type: int16
    factor: 0.1
    unit: "°C"
    device_class: "temperature"
  
  temperature_sensor_4:
    name: "Temperature Sensor 4"
    address: 5793  # Offset 258 (base 5664 + 129 regs = 5793)
    data_type: int16
    factor: 0.1
    unit: "°C"
    device_class: "temperature"

  # ===== Power and Current =====
  total_power:
    name: "Total Power"
    address: 5741  # Offset 154 (154/2 = 77), uint32le
    data_type: uint32
    factor: 0.001
    unit: "W"
    device_class: "power"
  
  total_current:
    name: "Total Current"
    address: 5743  # Offset 158 (158/2 = 79), int32le
    data_type: int32
    factor: 0.001
    unit: "A"
    device_class: "current"
  
  balance_current:
    name: "Balance Current"
    address: 5749  # Offset 170 (170/2 = 85)
    data_type: int16
    factor: 0.001
    unit: "A"
    device_class: "current"

  # ===== Voltage =====
  total_voltage:
    name: "Total Voltage"
    address: 5781  # Offset 234 (base 5664 + 117 regs = 5781)
    data_type: uint16
    factor: 0.01
    unit: "V"
    device_class: "voltage"

  # ===== State of Charge and Health =====
  state_of_charge:
    name: "State of Charge"
    address: 5750  # Offset 173 (base 5664 + 86 regs = 5750, but SOC is uint8 at odd offset)
    data_type: uint16
    factor: 0.00390625  # Divide by 256 to get the single byte value
    unit: "%"
    device_class: "battery"
  
  state_of_health:
    name: "State of Health"
    address: 5759  # Offset 190 (190/2 = 95)
    data_type: uint16
    factor: 1.0
    unit: "%"

  # ===== Capacity =====
  remaining_capacity:
    name: "Remaining Capacity"
    address: 5751  # Offset 174 (174/2 = 87), int32le
    data_type: int32
    factor: 0.001
    unit: "Ah"
  
  battery_capacity:
    name: "Battery Capacity"
    address: 5753  # Offset 178 (178/2 = 89), int32le
    data_type: int32
    factor: 0.001
    unit: "Ah"
  
  cycle_capacity:
    name: "Cycle Capacity"
    address: 5757  # Offset 186 (186/2 = 93), int32le
    data_type: int32
    factor: 0.001
    unit: "Ah"

  # ===== Cycle Count =====
  cycle_count:
    name: "Cycle Count"
    address: 5755  # Offset 182 (182/2 = 91), int32le
    data_type: int32
    factor: 1.0
    unit: ""

  # ===== Runtime =====
  total_runtime:
    name: "Total Runtime"
    address: 5761  # Offset 194 (194/2 = 97), uint32le
    data_type: uint32
    factor: 1.0
    unit: "s"

  # ===== Switches/Status =====
  charge_switch:
    name: "Charge Switch"
    address: 5763  # Offset 198 (198/2 = 99)
    data_type: uint16
    factor: 1.0
    unit: ""
  
  discharge_switch:
    name: "Discharge Switch"
    address: 5763  # Offset 199 (199/2 = 99.5, same register)
    data_type: uint16
    factor: 1.0
    unit: ""
  
  balance_switch:
    name: "Balance Switch"
    address: 5764  # Offset 200 (200/2 = 100)
    data_type: uint16
    factor: 1.0
    unit: ""
  
  balance_action:
    name: "Balance Action"
    address: 5750  # Offset 172 (172/2 = 86)
    data_type: uint16
    factor: 1.0
    unit: ""
